version: "3.8"
services: 
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=rise-dev-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    container_name: rise_database_container
    restart: always

  # # API services
  api: 
    image: rise
    ports: 
      - 3300:3300
    volumes:
      - .:/app
      - /app/node_modules

    environment:
      NODE_ENV: 'development'
      DEV_PORT: 3300
      DATABASE_DEV_STRING: 'postgres://postgres:supersecretpassword@db:5432/rise-dev-db'
      DEV_PAPERTRAIL_HOST: 'logs4.papertrailapp.com'
      DEV_PAPERTRAIL_PORT: 36518
      JWT_SECRET: 'somerandomekeynumberalpha'
    container_name: api
    depends_on: 
      - db