import 'dotenv/config';

const {
    DEV_PORT,
    NODE_ENV,
    DATABASE_DEV_STRING,
    DEV_PAPERTRAIL_HOST,
    DEV_PAPERTRAIL_PORT
} = process.env;

export default {
    PORT: DEV_PORT,
    NODE_ENV: NODE_ENV,
    DATABASE_STRING: DATABASE_DEV_STRING,
    PAPERTRAIL_HOST: DEV_PAPERTRAIL_HOST,
    PAPERTRAIL_PORT: DEV_PAPERTRAIL_PORT
}