import 'dotenv/config';

const {
    PROD_PORT,
    NODE_ENV,
    DATABASE_PROD_STRING,
    PROD_PAPERTRAIL_HOST,
    PROD_PAPERTRAIL_PORT
} = process.env;

export default {
    PORT: PROD_PORT,
    NODE_ENV: NODE_ENV,
    DATABASE_STRING: DATABASE_PROD_STRING,
    PAPERTRAIL_HOST: PROD_PAPERTRAIL_HOST,
    PAPERTRAIL_PORT: PROD_PAPERTRAIL_PORT
}