import 'dotenv/config';

const {
    TEST_PORT,
    NODE_ENV,
    DATABASE_TEST_STRING,
    TEST_PAPERTRAIL_HOST,
    TEST_PAPERTRAIL_PORT
} = process.env;

export default {
    PORT: TEST_PORT,
    NODE_ENV: NODE_ENV,
    DATABASE_STRING: DATABASE_TEST_STRING,
    PAPERTRAIL_HOST: TEST_PAPERTRAIL_HOST,
    PAPERTRAIL_PORT: TEST_PAPERTRAIL_PORT
}